#!/bin/bash


# slideshow requires zenity and feh to be installed
# 
# variable=$()  by wrapping the code in $(...) stores zenity output into a variable 
# 
# $? is the exit status (return) of the last executed command 
# 
# zenity 	returns (0 if user clicked ok)  
# 		returns (1 if user cancel or close window)
# 		returns (-1 an erro occured)
# 		returns (5 The dialog has been closed because the timeout has been reached.)





#store selected directory in FOLDER var
FOLDER=$(zenity --file-selection --title="Select the folder with your slide show images." --directory);

#store exit status of the last zenity command in FOLDER_SELECTED var
FOLDER_SELECTED=$?;

#if user selects a folder ask if user wants random mode (0 yes 1 no)
case $FOLDER_SELECTED in
         0)
                zenity --question --text="Do you want random order?";
            	RAND_ORD=$?;
            	FEH_CMD="feh ${FOLDER} --recursive --auto-rotate";;

         1)
                zenity --info --text="No folder selected.";;
        -1)
                zenity --error --text="An unexpected error has occurred.";;
esac

#ask if user wants fullscreen or adjustable window (0 yes 1 no)
case $RAND_ORD in 
		0)
			zenity --question --text="Do you want fullscreen mode or adjustable window? Yes for fullscreen.";
            FULL_SCREEN=$?;
            FEH_CMD="${FEH_CMD} --randomize";;        
		1)
			zenity --question --text="Do you want fullscreen mode or adjustable window? Yes for fullscreen.";
            FULL_SCREEN=$?;
            FEH_CMD="${FEH_CMD} --sort filename --version-sort";;
	   -1)
			
			zenity --error --text="An unexpected error has occurred.";;
esac

#ask user to select time (in seconds) for slideshow
case $FULL_SCREEN in
		0)
			TIME=$(zenity --entry --title="Slide Show" --text="Enter the delay time between slides. Default 1 second" --entry-text="1");
			CHOOSE_TIME=$?;
			FEH_CMD="${FEH_CMD} --fullscreen --auto-zoom";;
		1) 
			TIME=$(zenity --entry --title="Slide Show" --text="Enter the delay time between slides. Default 1 second" --entry-text="1");
			CHOOSE_TIME=$?;
			FEH_CMD="${FEH_CMD} --scale-down --auto-zoom";;
	   -1)
			zenity --error --text="An unexpected error has occurred.";;
esac

#if time choosen build feh command

case $CHOOSE_TIME in
		0)
			FEH_CMD="${FEH_CMD} --slideshow-delay ${TIME} --image-bg black";;
		1)
			FEH_CMD="${FEH_CMD} --slideshow-delay 1 --image-bg black";;
	   -1) 
			zenity --error --text="An unexpected error has occurred.";;
esac

echo $FEH_CMD;
$FEH_CMD;